name: swipe_away
description: SwipeAway - your guide to Romanian accommodations
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1

flutter:
  assets:
    - assets/icons/

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts:
  flutter_lints: ^3.0.0